% JR-2, 1. gyak
% Bevezetés/JR1 ismétlés

%% Szinuszos avg, effektív érték

U_s = 1;

T = 1;
w = 2*pi/T;
t = -1*T : 0.01*T : 1*T;

U_0 = 1;
U_1 = 4*U_s / (1*pi);
U_3 = 4*U_s / (3*pi);
U_5 = 4*U_s / (5*pi);
U_7 = 4*U_s / (7*pi);

size = 12;
figure(1)
title('Négyszögjel közelítése szinuszokkal')
set(gca,'fontsize',size)
xlabel('t','FontSize',size);
ylabel('Amplitúdó','FontSize',size);
xlim([-T,T]);
ylim([-1.5,2.5]);
grid on;
legend('Location','northeast','NumColumns',1,'FontSize',size);
hold on
plot(t,U_0 + U_1*sin(1*w*t) + U_3*sin(3*w*t),...
    'DisplayName','U_{0} + \Sigma_{1}^{3} U_{i}sin(\omega_{i}t)',...
    'LineStyle','-.',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,0.0]);
plot(t,U_0 + U_1*sin(1*w*t) + U_3*sin(3*w*t) + U_5*sin(5*w*t),...
    'DisplayName','U_{0} + \Sigma_{1}^{5} U_{i}sin(\omega_{i}t)',...
    'LineStyle','--',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,0.0]);
plot(t,U_0 + U_1*sin(1*w*t) + U_3*sin(3*w*t) + U_5*sin(5*w*t) + U_7*sin(7*w*t),...
    'DisplayName','U_{0} + \Sigma_{1}^{7} U_{i}sin(\omega_{i}t)',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,0.0]);
plot(t,U_0 + 0*t,...
    'DisplayName','U_{0}',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,1.0]);
plot(t,U_1*sin(1*w*t),...
    'DisplayName','U_{1}sin(\omega_{1}t)',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.2,0.8,0.2]);
plot(t,U_3*sin(3*w*t),...
    'DisplayName','U_{3}sin(\omega_{3}t)',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,0.0]);
plot(t,U_5*sin(5*w*t),...
    'DisplayName','U_{5}sin(\omega_{5}t)',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,1.0]);
hold off


%% Effektív feszültség

U_0 = 1;
U_1 = 4*U_s / (1*pi);
U_3 = 4*U_s / (3*pi);
U_5 = 4*U_s / (5*pi);
U_7 = 4*U_s / (7*pi);


U_eff = sqrt(U_0^2 + U_1^2/2 + U_3^2/2 + U_5^2/2 + U_7^2/2);
clc;
disp(['U_eff = ',num2str(U_eff,'%.3f'),' (p = 1,3,5,7)']);

%% Átviteli karakterisztika

R = 10;
C = 0.5;
w_max = 10;
w = 0 : 1 : w_max;

H = (1 + 1i*w*R*C)/R;

size = 12;
figure(1)
colororder({'k','k'});
title('Átviteli karakterisztika')
set(gca,'fontsize',size)
xlabel('\omega','FontSize',size);
ylabel('K(\omega)','FontSize',size);
%xlim([-T,T]);
%ylim([-1.5,2.5]);
grid on;
legend('Location','southeast','NumColumns',1,'FontSize',size);
hold on
plot(w,abs(H),...
    'DisplayName','K(\omega) = |H(j\omega)|',...
    'LineStyle','none',...
    'Marker','o',...
    'LineWidth',2,...
    'Color',[0.0,0.0,1.0]);
plot(w,w*C,...
    'DisplayName','\omega C',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',3,...
    'Color',[0.0,0.0,1.0]);
yyaxis("right")
ylabel('\phi(\omega)');
ylim([-pi/2,pi/2]);
yticks(-pi/2 : pi/4 : pi/2);
yticklabels({'-\pi/2','-\pi/4','0','\pi/4','\pi/2'})
plot(w,angle(H),...
    'DisplayName','\phi(w) = arc(H(j\omega))',...
    'LineStyle','none',...
    'Marker','o',...
    'LineWidth',3,...
    'Color',[1.0,0.0,0.0]);
plot(w,atan(w*R*C),...
    'DisplayName','tg^{-1}(\omega R C)',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,0.0]);
hold off

%% "Táblázatos" módszer

U_0 = 1;
H_0 = 0.1;
Y_0 = U_0*H_0;

w_max = 10;
w_p = 1 : 1 : w_max;

U_p = zeros([w_max,1]);
H_p = zeros([w_max,1]);
Y_p = zeros([w_max,1]);
for p = 1 : w_max
    if mod(p,2) == 1
        U_p(p) = 4*1/(p*pi);
    end
    H_p(p) = (1 + 1i*w_p(p)*R*C)/R;

    Y_p(p) = ( abs(U_p(p))*abs(H_p(p)) )*exp(1i*( angle(U_p(p)) + angle(H_p(p)) ));
end

w_p = [0, w_p];
U_p = [U_0; U_p];
H_p = [H_0; H_p];
Y_p = [Y_0; Y_p];

%% Válasz: absz. érték

size = 12;
figure(1)
colororder({'k','k'});
title('Válasz');
set(gca,'fontsize',size)
xlabel('\omega_{p}','FontSize',size);
ylabel('|Y_{p}|','FontSize',size);
%xlim([-T,T]);
%ylim([-1.5,2.5]);
grid on;
legend('Location','northwest','NumColumns',1,'FontSize',size);
hold on
plot(w_p,abs(U_p),...
    'DisplayName','|U_{p}|',...
    'LineStyle','none',...
    'Marker','*',...
    'LineWidth',3,...
    'Color',[0.0,0.0,1.0]);
plot(w_p,abs(H_p),...
    'DisplayName','|H_{p}|',...
    'LineStyle','none',...
    'Marker','o',...
    'LineWidth',3,...
    'Color',[1.0,0.0,0.0]);
plot(w_p,abs(Y_p),...
    'DisplayName','|Y_{p}|',...
    'LineStyle','none',...
    'Marker','+',...
    'LineWidth',2,...
    'Color',[0.0,0.0,0.0]);
hold off

%% Válaz: fázis

size = 12;
figure(2)
colororder({'k','k'});
title('Válasz');
set(gca,'fontsize',size)
xlabel('\omega_{p}','FontSize',size);
ylabel('arc(Y_{p})');
ylim([-pi/2,pi/2]);
yticks(-pi/2 : pi/4 : pi/2);
yticklabels({'-\pi/2','-\pi/4','0','\pi/4','\pi/2'})
grid on;
legend('Location','northwest','NumColumns',1,'FontSize',size);
hold on
ylabel('arc(Y_{p})');
ylim([-pi/2,pi/2]);
yticks(-pi/2 : pi/4 : pi/2);
yticklabels({'-\pi/2','-\pi/4','0','\pi/4','\pi/2'})
plot(w_p,angle(U_p),...
    'DisplayName','arc(U_{p})',...
    'LineStyle','none',...
    'Marker','*',...
    'LineWidth',3,...
    'Color',[0.0,0.0,1.0]);
plot(w_p,angle(H_p),...
    'DisplayName','arc(H_{p})',...
    'LineStyle','none',...
    'Marker','o',...
    'LineWidth',3,...
    'Color',[1.0,0.0,0.0]);
plot(w_p,angle(Y_p),...
    'DisplayName','arc(Y_{p})',...
    'LineStyle','none',...
    'Marker','+',...
    'LineWidth',3,...
    'Color',[0.0,0.0,0.0]);
hold off

%% Válasz: időfüggvény

T = 1;
w = 2*pi/T;
% idő
t = -1*T : 0.01*T : 1*T;




%%
y = Y_p(1) + abs(Y_p(2))*sin(1*w_p(2)*t + angle(Y_p(2)))...
    + abs(Y_p(4))*sin(3*w_p(4)*t + angle(Y_p(4)))...
    + abs(Y_p(6))*sin(5*w_p(6)*t + angle(Y_p(6)))...
    + abs(Y_p(8))*sin(7*w_p(8)*t + angle(Y_p(8)));


size = 12;
figure(1)
colororder({'k','k'});
title('Válasz');
set(gca,'fontsize',size)
xlabel('t','FontSize',size);
ylabel('y(t)','FontSize',size);
%xlim([-T,T]);
%ylim([-1.5,2.5]);
grid on;
legend('Location','northwest','NumColumns',1,'FontSize',size);
hold on
plot(t,y,...
    'DisplayName','y(t)',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',3,...
    'Color',[0.0,0.0,1.0]);
hold off









