% 10. Gyak (szombat, 10.18.)

%% Elsőfokú Bode alaptag - számlálóban

clc;
clear all;

% törésponti freki == zérushely
w_0 = 1;
w = logspace(-2,2,1000);

% alaptag
K = w_0*(1+1i*w/w_0);

size = 12;
figure(1)
title('Elsőfokú Bode alaptag - Számlálóban');
set(gca,'fontsize',size)
% --- x-axis ---
xlabel('\omega','FontSize',size);
xscale('log');
% --- y-axis ---
ylabel('k(\omega)','FontSize',size);
yscale('lin');
grid on;
legend('Location','northwest','NumColumns',1,'FontSize',size);
hold on
plot(w,20*log10(abs(K)),...
    'DisplayName',['\omega_{0} = ',num2str(w_0)],...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,1.0]);
yline(3,...
    'DisplayName','+3 dB',...
    'LineStyle','-.',...
    ...'Marker','none',...
    'LineWidth',2,...
    'Color',[0.5,0.5,0.5]);
hold off

figure(2)
title('Elsőfokú Bode alaptag - Számlálóban');
set(gca,'fontsize',size)
% --- x-axis ---
xlabel('\omega','FontSize',size);
xscale('log');
% --- y-axis ---
ylabel('\phi(\omega)','FontSize',size);
yscale('lin');
ylim([0,pi/2]);
yticks([0, pi/8, pi/4, 3*pi/8, pi/2]);
yticklabels({'0', '', '\pi/4', '', '\pi/2'});
grid on;
legend('Location','northwest','NumColumns',1,'FontSize',size);
hold on
plot(w,angle(K),...
    'DisplayName',['\omega_{0} = ',num2str(w_0)],...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,1.0]);
hold off

%% Elsőfokú Bode alaptag - nevezőben

clc;
clear all;

% törésponti freki == pólus
w_0 = 1;
w = logspace(-2,2,1000);

% alaptag
K = 1./(1+1i*w/w_0);

size = 12;
figure(1)
title('Elsőfokú Bode alaptag - Nevezőben');
set(gca,'fontsize',size)
% --- x-axis ---
xlabel('\omega','FontSize',size);
xscale('log');
% --- y-axis ---
ylabel('k(\omega)','FontSize',size);
yscale('lin');
grid on;
legend('Location','northeast','NumColumns',1,'FontSize',size);
hold on
plot(w,20*log10(abs(K)),...
    'DisplayName',['\omega_{0} = ',num2str(w_0)],...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,1.0]);
yline(-3,...
    'DisplayName','-3 dB',...
    'LineStyle','-.',...
    ...'Marker','none',...
    'LineWidth',2,...
    'Color',[0.5,0.5,0.5]);
hold off

figure(2)
title('Elsőfokú Bode alaptag - Nevezőben');
set(gca,'fontsize',size)
% --- x-axis ---
xlabel('\omega','FontSize',size);
xscale('log');
% --- y-axis ---
ylabel('\phi(\omega)','FontSize',size);
yscale('lin');
ylim([-pi/2,0]);
yticks([-pi/2, -3*pi/8, -pi/4, -pi/8, 0]);
yticklabels({'-\pi/2', '', '-\pi/4', '', '0'});
grid on;
legend('Location','northeast','NumColumns',1,'FontSize',size);
hold on
plot(w,angle(K),...
    'DisplayName',['\omega_{0} = ',num2str(w_0)],...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,1.0]);
hold off

%% Másodfokú Bode alaptag - számlálóban

clc;
clear all;

% törésponti freki == zérushely
w_0 = 1;
w = logspace(-2,2,1000);

% alaptag
zeta_2 = 2;
K_2 = (1+ 2*zeta_2*(1i*w/w_0) +(1i*w/w_0).^2);
zeta_1 = 1;
K_1 = (1+ 2*zeta_1*(1i*w/w_0) +(1i*w/w_0).^2);
zeta_05 = 0.5;
K_05 = (1+ 2*zeta_05*(1i*w/w_0) +(1i*w/w_0).^2);
zeta_01 = 0.1;
K_01 = (1+ 2*zeta_01*(1i*w/w_0) +(1i*w/w_0).^2);

size = 12;
figure(1)
title('Másodfokú Bode alaptag - számlálóban');
set(gca,'fontsize',size)
% --- x-axis ---
xlabel('\omega','FontSize',size);
xscale('log');
% --- y-axis ---
ylabel('k(\omega)','FontSize',size);
yscale('lin');
grid on;
legend('Location','northwest','NumColumns',1,'FontSize',size);
hold on
plot(w,20*log10(abs(K_2)),...
    'DisplayName',['\omega_{0} = ',num2str(w_0),', \zeta = ',num2str(zeta_2)],...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,1.0]);
plot(w,20*log10(abs(K_1)),...
    'DisplayName',['\omega_{0} = ',num2str(w_0),', \zeta = ',num2str(zeta_1)],...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,1.0]);
plot(w,20*log10(abs(K_05)),...
    'DisplayName',['\omega_{0} = ',num2str(w_0),', \zeta = ',num2str(zeta_05)],...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.2,0.8,0.2]);
plot(w,20*log10(abs(K_01)),...
    'DisplayName',['\omega_{0} = ',num2str(w_0),', \zeta = ',num2str(zeta_01)],...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,0.0]);
yline(6,...
    'DisplayName','+6 dB',...
    'LineStyle','-.',...
    ...'Marker','none',...
    'LineWidth',2,...
    'Color',[0.5,0.5,0.5]);
hold off

figure(2)
title('Másodfokú Bode alaptag - Számlálóban');
set(gca,'fontsize',size)
% --- x-axis ---
xlabel('\omega','FontSize',size);
xscale('log');
% --- y-axis ---
ylabel('\phi(\omega)','FontSize',size);
yscale('lin');
ylim([0,pi]);
yticks([0, pi/8, pi/4, 3*pi/8, pi/2, 5*pi/8, 3*pi/4, 7*pi/8, pi]);
yticklabels({'0', '', '\pi/4', '', '\pi/2', '', '3\pi/4','','\pi'});
grid on;
legend('Location','northwest','NumColumns',1,'FontSize',size);
hold on
plot(w,angle(K_2),...
    'DisplayName',['\omega_{0} = ',num2str(w_0),', \zeta = ',num2str(zeta_2)],...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,1.0]);
plot(w,angle(K_1),...
    'DisplayName',['\omega_{0} = ',num2str(w_0),', \zeta = ',num2str(zeta_1)],...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,1.0]);
plot(w,angle(K_05),...
    'DisplayName',['\omega_{0} = ',num2str(w_0),', \zeta = ',num2str(zeta_05)],...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.2,0.8,0.2]);
plot(w,angle(K_01),...
    'DisplayName',['\omega_{0} = ',num2str(w_0),', \zeta = ',num2str(zeta_01)],...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,0.0]);
hold off


%% Másodfokú Bode alaptag - nevezőben

clc;
clear all;

% törésponti freki == zérushely
w_0 = 1;
w = logspace(-2,2,1000);

% alaptag
zeta_2 = 2;
K_2 = 1./(1+ 2*zeta_2*(1i*w/w_0) +(1i*w/w_0).^2);
zeta_1 = 1;
K_1 = 1./(1+ 2*zeta_1*(1i*w/w_0) +(1i*w/w_0).^2);
zeta_05 = 0.5;
K_05 = 1./(1+ 2*zeta_05*(1i*w/w_0) +(1i*w/w_0).^2);
zeta_01 = 0.1;
K_01 = 1./(1+ 2*zeta_01*(1i*w/w_0) +(1i*w/w_0).^2);

size = 12;
figure(1)
title('Másodfokú Bode alaptag - Nevezőben');
set(gca,'fontsize',size)
% --- x-axis ---
xlabel('\omega','FontSize',size);
xscale('log');
% --- y-axis ---
ylabel('k(\omega)','FontSize',size);
yscale('lin');
grid on;
legend('Location','southwest','NumColumns',1,'FontSize',size);
hold on
plot(w,20*log10(abs(K_2)),...
    'DisplayName',['\omega_{0} = ',num2str(w_0),', \zeta = ',num2str(zeta_2)],...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,1.0]);
plot(w,20*log10(abs(K_1)),...
    'DisplayName',['\omega_{0} = ',num2str(w_0),', \zeta = ',num2str(zeta_1)],...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,1.0]);
plot(w,20*log10(abs(K_05)),...
    'DisplayName',['\omega_{0} = ',num2str(w_0),', \zeta = ',num2str(zeta_05)],...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.2,0.8,0.2]);
plot(w,20*log10(abs(K_01)),...
    'DisplayName',['\omega_{0} = ',num2str(w_0),', \zeta = ',num2str(zeta_01)],...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,0.0]);
yline(-6,...
    'DisplayName','-6 dB',...
    'LineStyle','-.',...
    ...'Marker','none',...
    'LineWidth',2,...
    'Color',[0.5,0.5,0.5]);
hold off

figure(2)
title('Elsőfokú Bode alaptag - Nevezőben');
set(gca,'fontsize',size)
% --- x-axis ---
xlabel('\omega','FontSize',size);
xscale('log');
% --- y-axis ---
ylabel('\phi(\omega)','FontSize',size);
yscale('lin');
ylim([-pi,0]);
yticks([-pi, -7*pi/8, -3*pi/4, -5*pi/8, -pi/2, -3*pi/8, -pi/4, -pi/8, 0]);
yticklabels({'-\pi', '', '-3\pi/4', '', '-\pi/2', '', '-\pi/4', '', '0'});
grid on;
legend('Location','northeast','NumColumns',1,'FontSize',size);
hold on
plot(w,angle(K_2),...
    'DisplayName',['\omega_{0} = ',num2str(w_0),', \zeta = ',num2str(zeta_2)],...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,1.0]);
plot(w,angle(K_1),...
    'DisplayName',['\omega_{0} = ',num2str(w_0),', \zeta = ',num2str(zeta_1)],...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,1.0]);
plot(w,angle(K_05),...
    'DisplayName',['\omega_{0} = ',num2str(w_0),', \zeta = ',num2str(zeta_05)],...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.2,0.8,0.2]);
plot(w,angle(K_01),...
    'DisplayName',['\omega_{0} = ',num2str(w_0),', \zeta = ',num2str(zeta_01)],...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,0.0]);
hold off


%% Példa - elsőfok

clc;
clear all;

w = logspace(-2,2,1000);

% alaptag
K = 2 * (1+1i*w/1) * 1./(1+1i*w/10) * 1./(1+1i*w/0.2);

size = 12;
figure(1)
%title('');
set(gca,'fontsize',size)
% --- x-axis ---
xlabel('\omega','FontSize',size);
xscale('log');
% --- y-axis ---
ylabel('k(\omega)','FontSize',size);
yscale('lin');
grid on;
legend('Location','northwest','NumColumns',1,'FontSize',size);
hold on
yline(20*log10(2),...
    'DisplayName','k_{0}',...
    'LineStyle','-',...
    'LineWidth',2,...
    'Color',[1.0,0.0,1.0]);
plot(w,20*log10(abs( (1+1i*w/1) )),...
    'DisplayName','k_{1}(\omega), \omega_{1} = 1',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,1.0]);
plot(w,20*log10(abs( 1./(1+1i*w/10) )),...
    'DisplayName','k_{2}(\omega), \omega_{2} = 10',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.2,0.8,0.2]);
plot(w,20*log10(abs( 1./(1+1i*w/0.2) )),...
    'DisplayName','k_{3}(\omega), \omega_{3} = 0.2',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,0.0]);
plot(w,20*log10(abs( K )),...
    'DisplayName','k(\omega)',...
    'LineStyle','-.',...
    'Marker','none',...
    'LineWidth',3,...
    'Color',[0.0,0.0,0.0]);
hold off

figure(2)
%title('');
set(gca,'fontsize',size)
% --- x-axis ---
xlabel('\omega','FontSize',size);
xscale('log');
% --- y-axis ---
ylabel('\phi(\omega)','FontSize',size);
yscale('lin');
ylim([-pi/2,pi/2]);
yticks([-pi/2, -3*pi/8, -pi/4, -pi/8, 0, pi/8, pi/4, 3*pi/8, pi/2]);
yticklabels({'-\pi/2', '', '-\pi/4', '', '0', '', '\pi/4', '', '\pi/2'})
grid on;
legend('Location','northeast','NumColumns',1,'FontSize',size);
hold on
plot(w,angle( (1+1i*w/1) ),...
    'DisplayName','\phi_{1}(\omega), \omega_{1} = 1',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,1.0]);
plot(w,angle( 1./(1+1i*w/10) ),...
    'DisplayName','\phi_{2}(\omega), \omega_{2} = 10',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.2,0.8,0.2]);
plot(w,angle( 1./(1+1i*w/0.2) ),...
    'DisplayName','\phi_{3}(\omega), \omega_{3} = 0.2',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,0.0]);
plot(w,angle( K ),...
    'DisplayName','\phi(\omega)',...
    'LineStyle','-.',...
    'Marker','none',...
    'LineWidth',3,...
    'Color',[0.0,0.0,0.0]);
hold off



%% Példa - másdfok

clc;
clear all;

w = logspace(-2,4,1000);

% alaptag
K = ( (1+1i*w/1000).*(1+1i*w/10).^2 )./( (1+1i*w/0.1).^2 );
%K = ( (1+1i*w/10000).* (1+1i*w/100).*(1+1i*w/100) )./((1+1i*w/0.1).*(1+1i*w/0.1));
size = 12;
figure(1)
title('Példa másodfokúra');
set(gca,'fontsize',size)
% --- x-axis ---
xlabel('\omega','FontSize',size);
xscale('log');
% --- y-axis ---
ylabel('k(\omega)','FontSize',size);
yscale('lin');
grid on;
legend('Location','northwest','NumColumns',1,'FontSize',size);
hold on
%{
yline(20*log10(2),...
    'DisplayName','k_{0}',...
    'LineStyle','-',...
    'LineWidth',2,...
    'Color',[1.0,0.0,1.0]);
%}
plot(w,20*log10(abs( (1+1i*w/1000) )),...
    'DisplayName','k_{1}(\omega), \omega_{1} = 1000',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,1.0]);
plot(w,20*log10(abs( (1+1i*w/10).^2 )),...
    'DisplayName','k_{2}(\omega), \omega_{2} = 10',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.2,0.8,0.2]);
plot(w,20*log10(abs( 1./(1+1i*w/0.1).^2 )),...
    'DisplayName','k_{3}(\omega), \omega_{3} = 0.1',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,0.0]);
plot(w,20*log10(abs( K )),...
    'DisplayName','k(\omega)',...
    'LineStyle','-.',...
    'Marker','none',...
    'LineWidth',3,...
    'Color',[0.0,0.0,0.0]);
hold off

figure(2)
%title('');
set(gca,'fontsize',size)
% --- x-axis ---
xlabel('\omega','FontSize',size);
xscale('log');
% --- y-axis ---
ylabel('\phi(\omega)','FontSize',size);
yscale('lin');
ylim([-pi,pi]);
yticks([-pi, -7*pi/8, -3*pi/4, -5*pi/8, -pi/2, -3*pi/8, -pi/4, -pi/8, 0,...
    pi/8, pi/4, 3*pi/8, pi/2, 5*pi/8, 3*pi/4, 7*pi/8, pi]);
yticklabels({'-\pi', '', '-3\pi/4', '', '-\pi/2', '', '-\pi/4', '', '0',...
    '', '\pi/4', '', '\pi/2', '', '3\pi/4','','\pi'});
grid on;
legend('Location','northeast','NumColumns',1,'FontSize',size);
hold on
plot(w,angle( (1+1i*w/1000) ),...
    'DisplayName','\phi_{1}(\omega), \omega_{1} = 1000',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,1.0]);
plot(w,angle((1+1i*w/10).^2 ),...
    'DisplayName','\phi_{2}(\omega), \omega_{2} = 10',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.2,0.8,0.2]);
plot(w,angle( 1./(1+1i*w/0.1).^2 ),...
    'DisplayName','\phi_{3}(\omega), \omega_{3} = 0.1',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,0.0]);
plot(w,angle( K ),...
    'DisplayName','\phi(\omega)',...
    'LineStyle','-.',...
    'Marker','none',...
    'LineWidth',3,...
    'Color',[0.0,0.0,0.0]);
hold off


