% JR-2, 5. gyakorlat (09.29.)


%% Sávszélesség négyszögimpulzusra

clc;
clear all;

sigma = 0.1;
A = 1;
tau = 10;

w = 0.05 : 0.05 : 10;
U = A*tau*sin(w*tau/2)./(w*tau/2);
U_env = A*2./w;
w = [-flip(w),0,w];
U = [flip(U),A*tau,U];
U_env = [flip(U_env),NaN,U_env];

w_max = 2/(sigma*tau);

size = 12;
figure(2)
title('négyszögimpulzus - sávkorlát');
set(gca,'fontsize',size)
xlabel('\omega [MHz]','FontSize',size);
ylabel('U(j\omega) [Vs]','FontSize',size);
ylim([0,A*tau]);
grid on;
legend('Location','northeast','NumColumns',1,'FontSize',size);
hold on
plot(w,abs(U),...
    'DisplayName','|U(j\omega)| = |A*\tau * sin(\omega \tau/2)/(\omega \tau/2)|',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,1.0]);
plot(w,abs(U_env),...
    'DisplayName','|U(j\omega)_{env}| = A * 2/\omega',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,0.0]);
yline(sigma*max(abs(U)), ...
    'DisplayName','\sigma |U(j\omega)|_{max} = \sigma * A * \tau', ...
    'LineStyle','-.',...
    'LineWidth',2,...
    'Color',[0.5,0.5,0.5])
%num2str(sigma*max(abs(U)))

xline(-w_max, ...
    'DisplayName',['-\omega_{max} = ',num2str(-w_max,'%.3f'), '[MHz]'], ...
    'LineStyle','-.',...
    'LineWidth',2,...
    'Color',[0.5,0.5,0.5])
xline(w_max, ...
    'DisplayName',['\omega_{max} = ',num2str(w_max,'%.3f'),' [MHz]'], ...
    'LineStyle','-.',...
    'LineWidth',2,...
    'Color',[0.5,0.5,0.5])
%}
hold off

%% Elsőfokú szűrő
clc;
clear all;

w = 0 : 0.1 : 1000;
R = 2;
L = 1;
C = 0.1;

% Alulátersztő jelleg: sorba kötött tekercs vagy párhuzamos kondi
% Tekercs: kisfrekin:   "csak egy drót", mindent átenged
%          nagyfrekin:  jwL-szerint növekedő imp, egyre kevésbé enged át
%          +inf frekin: semmint nem enged át, "szinte szakadás"
% Kondi: kisfrekin:   "szinte szaakdás", semmit nem szív le
%        nagyfrekin:  1/jwC-szerint csökkenő imp, egyre többet leszív
%        +inf frekin: mindent leszív, "tökéletes rövidzár"

H = 2*R ./ (1i*w*R*2*R*C + 2*R + R);


% gerjesztés
A = 1;
lam = 0.5;
% Dirac-delta gerjesztés:
U_1 = 0*w + A * 1;
% Belépő, lecsengő gerjesztés:
U_1 = A./(lam + 1i*w);
%U_1 = A*tau*sin(w*tau/2)./(w*tau/2).*exp(-1i*w*tau/2);

% Válaszjel
U_2 = H.*U_1;


size = 12;
figure(1)
%title('Fel- és lefutó négyszögimpulzus (frekiben)');
set(gca,'fontsize',size)
xlabel('\omega','FontSize',size);
xlim([0,25]);
ylabel('|F(j\omega)|','FontSize',size);
grid on;
legend('Location','northeast','NumColumns',1,'FontSize',size);
hold on
plot(w,abs(U_1),...
    'DisplayName','U_{1}(j\omega) - gerjesztés',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,1.0]);
plot(w,abs(H),...
    'DisplayName','H(j\omega) - szűrő',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.2,0.8,0.2]);
plot(w,abs(U_2),...
    'DisplayName','U_{2}(j\omega) - válasz',...
    'LineStyle','-.',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,0.0]);
hold off;

% dB-ben kifejezett érték: k^{dB} = 20*log(K)
% továbbá: w-tengely logaritmikusan ábrázolva
size = 12;
figure(2)
set(gca,'fontsize',size)
xlabel('\omega','FontSize',size);
xscale('log');
xlim([0.1,1000])
ylabel('|F(j\omega)| [dB]','FontSize',size);
grid on;
legend('Location','northeast','NumColumns',1,'FontSize',size);
hold on
plot(w,20*log10(abs(U_1)),...
    'DisplayName','U_{1}(j\omega) - gerjesztés',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,1.0]);
plot(w,20*log10(abs(H)),...
    'DisplayName','H(j\omega) - szűrő',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.2,0.8,0.2]);
plot(w,20*log10(abs(U_2)),...
    'DisplayName','U_{2}(j\omega) - válasz',...
    'LineStyle','-.',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,0.0]);
hold off;


%% Elsőfokú szűrő - négyszögjel gerjesztés

clc;
clear all;

w = 0 : 0.1 : 1000;
R = 2;
L = 1;
C = 0.1;

% alulátersztő jelleg
H = 2*R ./ (1i*w*R*2*R*C + 2*R + R);

% gerjesztés
A = 1;
tau = 1;
U_1 = A*tau*sin(w*tau/2)./(w*tau/2).*exp(-1i*w*tau/2);

% Válaszjel
U_2 = H.*U_1;

size = 12;
figure(1)
%title('Fel- és lefutó négyszögimpulzus (frekiben)');
set(gca,'fontsize',size)
xlabel('\omega','FontSize',size);
xlim([0,25]);
ylabel('|F(j\omega)|','FontSize',size);
grid on;
legend('Location','northeast','NumColumns',1,'FontSize',size);
hold on
plot(w,abs(U_1),...
    'DisplayName','U_{1}(j\omega) - gerjesztés',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,1.0]);
plot(w,abs(H),...
    'DisplayName','H(j\omega) - szűrő',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.2,0.8,0.2]);
plot(w,abs(U_2),...
    'DisplayName','U_{2}(j\omega) - válasz',...
    'LineStyle','-.',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,0.0]);
hold off;

% dB-ben kifejezett érték: k^{dB} = 20*log(K)
% továbbá: w-tengely logaritmikusan ábrázolva
size = 12;
figure(2)
set(gca,'fontsize',size)
xlabel('log(\omega)','FontSize',size);
xscale('log');
xlim([0.1,1000])
ylabel('|F(j\omega)| [dB]','FontSize',size);
grid on;
legend('Location','northeast','NumColumns',1,'FontSize',size);
hold on
plot(w,20*log10(abs(U_1)),...
    'DisplayName','U_{1}(j\omega) - gerjesztés',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,1.0]);
plot(w,20*log10(abs(H)),...
    'DisplayName','H(j\omega) - szűrő',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.2,0.8,0.2]);
plot(w,20*log10(abs(U_2)),...
    'DisplayName','U_{2}(j\omega) - válasz',...
    'LineStyle','-.',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,0.0]);
hold off;

%% Másodfokú szűrő

clc;
clear all;

w = 0 : 0.01 : 1000;
R_1 = 2;
R_2 = 3;
L = 1;
C = 0.1;

% aluláteresztés szűrő
H_a = (1/(L*C))./( ...
    (1i*w).^2 + ...
    (1/(R_2*C) + R_1/L)*(1i*w) + ...
    ((R_1 + R_2)/(R_2*L*C)) );

H_f = (1i*w).^2 ./( ...
    (1i*w).^2 + ...
    (1/(R_1*C))*(1i*w) + ...
    (1/(L*C)) );

size = 12;
figure(1)
title('Másodfokú szűrők');
set(gca,'fontsize',size)
xlabel('\omega','FontSize',size);
xlim([0,25]);
ylabel('|H(j\omega)|','FontSize',size);
grid on;
legend('Location','northeast','NumColumns',1,'FontSize',size);
hold on
plot(w,abs(H_a),...
    'DisplayName','Aluláteresztő',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,1.0]);
plot(w,abs(H_f),...
    'DisplayName','Felüláteresztő',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,0.0]);
hold off

size = 12;
figure(2)
title('Másodfokú szűrők');
set(gca,'fontsize',size)
xlabel('log(\omega)','FontSize',size);
%xlim([0,25]);
xscale('log');
ylabel('|H(j\omega)| [dB]','FontSize',size);
grid on;
legend('Location','northeast','NumColumns',1,'FontSize',size);
hold on
plot(w,20*log10(abs(H_a)),...
    'DisplayName','Aluláteresztő',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,1.0]);
plot(w,20*log10(abs(H_f)),...
    'DisplayName','Felüláteresztő',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,0.0]);
hold off


%% Elsőfokú Bode-tagok

clc;
clear all;

w = logspace(-2,4);
a_1 = 1;
a_2 = 100;
a_3 = 10;
a_4 = 0.1;

K_0 = 2 + 0*w;
K_1 = abs(1i*w + a_1);
K_2 = abs(1i*w + a_2);
K_3 = abs(1./(1i*w + a_3));
K_4 = abs(1./(1i*w + a_4));

phi_0 = angle(2 + 0*w);
phi_1 = angle(1i*w + a_1);
phi_2 = angle(1i*w + a_2);
phi_3 = angle(1./(1i*w + a_3));
phi_4 = angle(1./(1i*w + a_4));

% Erősítési karakterisztikák:
% K = K_0 * K_1(w) * K_2(w) * K_3(w) * K_4(w)
% k = k_0 + k_1(w) + k_2(w) + k_3(w) + k_4(w)

% Fáziskarakterisztikák:
% phi = phi_0 + phi_1(w) + phi_2(w) + phi_3(w) + phi_4(w)

size = 12;
figure(1)
title('Elsőfokú Bode-tagok');
set(gca,'fontsize',size)
xlabel('log(\omega)','FontSize',size);
%xlim([0,25]);
xscale('log');
ylabel('|H(j\omega)| [dB]','FontSize',size);
grid on;
legend('Location','northeast','NumColumns',1,'FontSize',size);
hold on
text(0.02,95,'Számlálóbeli tagok');
text(0.02,85,'K_{i}(\omega) = (j\omega + A_{i}) = A_{i}(j\omega/A_{i} +1)');
text(0.02,75,'k_{i}^{dB}(\omega) = 20log(K_{i}(\omega)) = 20log(A_{i}) + 20log(j\omega/A_{i} +1)');
text(0.02,65,'k_{i}^{dB}(\omega) = a_{i}^{dB} + 20log(j\omega/A_{i} +1)');
text(0.02,-35,'Nevezőbeli tagok')
text(0.02,-45,'K_{i}(\omega) = 1/(j\omega + A_{i}) = 1/( A_{i}(j\omega/A_{i} +1) )');
text(0.02,-55,'k_{i}^{dB}(\omega) = 20log(K_{i}(\omega)) = 20log(1/A_{i}) + 20log( 1/(j\omega/A_{i} +1) )');
text(0.02,-65,'k_{i}^{dB}(\omega) = -20log(A_{i}) - 20log( j\omega/A_{i} +1 )');
text(0.02,-75,'k_{i}^{dB}(\omega) = a_{i}^{dB} - 20log(j\omega/A_{i} +1)')
plot(w,20*log10(K_1),...
    'DisplayName','k_{1}^{dB}(\omega), A_{1} = 1, a_{1}^{dB} = 0',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,1.0]);
plot(w,20*log10(K_2),...
    'DisplayName','k_{2}^{dB}(\omega), A_{2} = 100, a_{2}^{dB} = +40',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,0.0]);
plot(w,20*log10(K_3),...
    'DisplayName','k_{3}^{dB}(\omega), A_{3} = 1/10, a_{3}^{dB} = -20',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.2,0.8,0.2]);
plot(w,20*log10(K_4),...
    'DisplayName','k_{4}^{dB}(\omega), A_{4} = 1/0.1, a_{4}^{dB} = +20',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,1.0]);
plot(w,20*log10(K_0),...
    'DisplayName','k_{0}^{dB} = 6dB (K_{0} = 2)',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,0.0]);
hold off

size = 12;
figure(2)
title('Elsőfokú Bode-tagok');
set(gca,'fontsize',size)
xlabel('log(\omega)','FontSize',size);
%xlim([0,25]);
xscale('log');
ylabel('\Phi(j\omega) [dB]','FontSize',size);
ylim([-pi/2,pi/2]);
yticks([-pi/2, -pi/4, 0, pi/4, pi/2]);
yticklabels({'-\pi/2','-\pi/4','0','\pi/4','\pi/2'})
grid on;
legend('Location','northeast','NumColumns',1,'FontSize',size);
hold on
plot(w,phi_1,...
    'DisplayName','\Phi_{1}(\omega)',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,1.0]);
plot(w,phi_2,...
    'DisplayName','\Phi_{2}(\omega)',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,0.0]);
plot(w,phi_3,...
    'DisplayName','\Phi_{3}(\omega)',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.2,0.8,0.2]);
plot(w,phi_4,...
    'DisplayName','\Phi_{4}(\omega)',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[1.0,0.0,1.0]);
plot(w,phi_0,...
    'DisplayName',';\Phi_{0}',...
    'LineStyle','-',...
    'Marker','none',...
    'LineWidth',2,...
    'Color',[0.0,0.0,0.0]);
hold off

